plugins {
    id 'com.android.application'
}

android {
    namespace 'com.emulador.xmb'
    compileSdk 34

    defaultConfig {
        applicationId "com.emulador.xmb"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"

        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
    }
}
